# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNC1DS1IC1DCI1DCO1P1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_nC1DS1IC1DCI1DCO1P1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@2")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").send_keys("Salerno")
    self.driver.find_element(By.ID, "nutton").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(6) .img-fluid").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.ID, "mese_scadenza").click()
    dropdown = self.driver.find_element(By.ID, "mese_scadenza")
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    self.driver.find_element(By.ID, "lastCheckInDate").click()
    self.driver.find_element(By.ID, "lastCheckInDate").clear()
    time.sleep(delay)
    self.driver.find_element(By.ID, "lastCheckInDate").send_keys("2028-11-23")
    self.driver.find_element(By.ID, "lastCheckInDate").click()
    self.driver.find_element(By.ID, "lastCheckInDate").clear()
    self.driver.find_element(By.ID, "lastCheckInDate").send_keys("23-12-2028")
    self.driver.find_element(By.ID, "lastCheckInDate").click()

    self.driver.find_element(By.ID, "lastCheckOutDate").click()
    self.driver.find_element(By.ID, "lastCheckOutDate").clear()
    self.driver.find_element(By.ID, "lastCheckOutDate").send_keys("28-05-2029")
    time.sleep(delay)
    self.driver.find_element(By.ID, "confermaPagamentoBtn").click()
    time.sleep(delay)
  
