# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT2D2P1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t2D2P1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("laurawhite@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("LauWhitelock124.")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle").click()
    self.driver.find_element(By.LINK_TEXT, "Recensione").click()
    self.driver.find_element(By.ID, "titolo").click()
    self.driver.find_element(By.ID, "titolo").send_keys("Casa molto accogliente")
    self.driver.find_element(By.ID, "descrizione").click()
    self.driver.find_element(By.ID, "descrizione").send_keys("Una casa perfetta, vicino l’università!")
    self.driver.find_element(By.ID, "mioBottone").click()
    time.sleep(delay)
    assert self.driver.switch_to.alert.text == "Non sono passati 30 giorni!"
  
