# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTCSSegnalazioneM1D2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tCSSegnalazioneM1D2(self):
    self.driver.get("http://127.0.0.1:5000/Segnala")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox-group:nth-child(1) > .custom-control:nth-child(1) > .custom-control-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox-group:nth-child(1) > .custom-control:nth-child(2) > .custom-control-label").click()
    assert self.driver.switch_to.alert.text == "Puoi scegliere un solo motivo. Deseleziona le altre caselle di controllo."
  
