# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.common import InvalidArgumentException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities




class TestT1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("andreaconti@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("And@99pass.")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.ID, "search2").click()
    self.driver.find_element(By.ID, "titolo").click()
    self.driver.find_element(By.ID, "titolo").send_keys("sds")
    self.driver.find_element(By.ID, "citta").click()
    self.driver.find_element(By.ID, "citta").send_keys("Salerno")
    self.driver.find_element(By.ID, "provincia").click()
    self.driver.find_element(By.ID, "provincia").send_keys("SA")
    self.driver.find_element(By.ID, "cap").send_keys("84025")
    self.driver.find_element(By.ID, "indirizzo").send_keys("Vito Albanese")
    self.driver.find_element(By.ID, "civico").click()
    self.driver.find_element(By.ID, "civico").send_keys("6")
    self.driver.find_element(By.ID, "tipo").click()
    dropdown = self.driver.find_element(By.ID, "tipo")
    dropdown.find_element(By.XPATH, "//option[. = 'Bilocale']").click()
    self.driver.find_element(By.ID, "Descrizione").click()
    self.driver.find_element(By.ID, "Descrizione").send_keys("fgjzojdkhfsiuroghesrdijghwesrioughbWòEOIUGFJHWSROIKJFGàopwi")
    self.driver.find_element(By.ID, "num_bagni").send_keys("9")
    self.driver.find_element(By.ID, "num_bagni").click()
    self.driver.find_element(By.ID, "num_camere").send_keys("13")
    self.driver.find_element(By.ID, "num_camere").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .custom-control-label").click()
    self.driver.find_element(By.ID, "num_ospiti").send_keys("9")
    self.driver.find_element(By.ID, "num_ospiti").click()
    self.driver.find_element(By.ID, "classe_energetica").click()
    self.driver.find_element(By.ID, "metri_quadri").send_keys("10")
    self.driver.find_element(By.ID, "metri_quadri").click()
    self.driver.find_element(By.ID, "prezzo").send_keys("26")
    self.driver.find_element(By.ID, "prezzo").click()
    self.driver.find_element(By.ID, "periodo_minimo").send_keys("1")
    self.driver.find_element(By.ID, "periodo_minimo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-check:nth-child(3) > .form-check-label").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "lista_immagini").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "lista_immagini").send_keys("C:/fakepath/prova1.png")
    time.sleep(delay)
    self.driver.find_element(By.ID, "MioBottone").click()
    assert self.driver.switch_to.alert.text == "Inserisci il titolo!"
  
