# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestP2U1NC2A1M2CV2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_p2U1NC2A1M2CV2(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@2")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle > path:nth-child(1)").click()
    self.driver.find_element(By.ID, "cc-number").click()
    self.driver.find_element(By.ID, "cc-number").send_keys("3546746378291037")
    self.driver.find_element(By.ID, "mese_scadenza").click()
    dropdown = self.driver.find_element(By.ID, "mese_scadenza")
    dropdown.find_element(By.XPATH, "//option[. = '8']").click()
    self.driver.find_element(By.ID, "scadenza").click()
    dropdown = self.driver.find_element(By.ID, "scadenza")
    dropdown.find_element(By.XPATH, "//option[. = '2028']").click()
    self.driver.find_element(By.ID, "modificaDatiBtn").click()
  
