# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestP1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_p1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle").click()
    self.driver.find_element(By.ID, "mese_scadenza").click()
    dropdown = self.driver.find_element(By.ID, "mese_scadenza")
    dropdown.find_element(By.XPATH, "//option[. = '5']").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").clear()
    self.driver.find_element(By.ID, "password").send_keys("12")
    self.driver.find_element(By.ID, "modificaDatiBtn").click()
    assert self.driver.switch_to.alert.text == "La password non è valida. Assicurati di rispettare tutti i requisiti."
  
  def test_p2U1NC1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle > path:nth-child(1)").click()
    self.driver.find_element(By.ID, "cc-number").click()
    self.driver.find_element(By.ID, "cc-number").clear()
    self.driver.find_element(By.ID, "cc-number").send_keys("3546746378")
    self.driver.find_element(By.ID, "mese_scadenza").click()
    dropdown = self.driver.find_element(By.ID, "mese_scadenza")
    dropdown.find_element(By.XPATH, "//option[. = '5']").click()
    self.driver.find_element(By.ID, "modificaDatiBtn").click()
    assert self.driver.switch_to.alert.text == "il Numero di carta deve avere 16 cifre"


  def test_p2U1NC2A1M1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle").click()
    self.driver.find_element(By.ID, "mese_scadenza").click()
    self.driver.find_element(By.ID, "scadenza").click()
    self.driver.find_element(By.ID, "modificaDatiBtn").click()
    assert self.driver.switch_to.alert.text == "Carta Scaduta"

  def test_p2U1NC2A1M2CV1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle > path:nth-child(1)").click()
    self.driver.find_element(By.ID, "cc-cvv").click()
    self.driver.find_element(By.ID, "cc-cvv").clear()
    self.driver.find_element(By.ID, "cc-cvv").send_keys("1")
    self.driver.find_element(By.ID, "mese_scadenza").click()
    dropdown = self.driver.find_element(By.ID, "mese_scadenza")
    dropdown.find_element(By.XPATH, "//option[. = '7']").click()
    self.driver.find_element(By.ID, "modificaDatiBtn").click()
    assert self.driver.switch_to.alert.text == "il cvv non ha tre cifre"

  def test_p2U1NC2A1M2CV2(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    time.sleep(delay)
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle > path:nth-child(1)").click()
    self.driver.find_element(By.ID, "cc-number").click()
    self.driver.find_element(By.ID, "cc-number").send_keys("3546746378291037")
    self.driver.find_element(By.ID, "mese_scadenza").click()
    dropdown = self.driver.find_element(By.ID, "mese_scadenza")
    dropdown.find_element(By.XPATH, "//option[. = '8']").click()
    self.driver.find_element(By.ID, "scadenza").click()
    dropdown = self.driver.find_element(By.ID, "scadenza")
    dropdown.find_element(By.XPATH, "//option[. = '2028']").click()
    self.driver.find_element(By.ID, "modificaDatiBtn").click()


