# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestM1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_m1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle").click()
    self.driver.find_element(By.LINK_TEXT, "Dettagli").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bottone > .btn").click()
    assert self.driver.switch_to.alert.text == "Non hai compilato nessun form. Compila almeno una checkbox e il campo di descrizione."

  def test_m1D2(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle > path:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Dettagli").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(5)").click()
    self.driver.find_element(By.ID, "Descrizione").click()
    self.driver.find_element(By.ID, "Descrizione").send_keys(
      "dhiuaeghfisuaedfhswedioufhsdoiufhsdiupofghsduifghsfdriugfhsdfiupghdsfpiug")
    self.driver.find_element(By.CSS_SELECTOR, ".bottone > .btn").click()
    assert self.driver.switch_to.alert.text == "Non hai compilato nessun form. Compila almeno una checkbox e il campo di descrizione."

  def test_m3D1(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle").click()
    self.driver.find_element(By.LINK_TEXT, "Dettagli").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox-group:nth-child(1) > .custom-control:nth-child(1) > .custom-control-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bottone > .btn").click()
    assert self.driver.switch_to.alert.text == "Non hai compilato nessun form. Compila almeno una checkbox e il campo di descrizione."


  def test_m3D2(self):
    delay = 5.0
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1265, 1372)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    time.sleep(delay)
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormEmail1").send_keys("sofiaesposito@gmail.com")
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").click()
    self.driver.find_element(By.ID, "exampleDropdownFormPassword1").send_keys("Passsofy1@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person-circle > path:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Dettagli").click()
    self.driver.execute_script("window.scrollTo(0,1500)")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox-group:nth-child(1) > .custom-control:nth-child(1) > .custom-control-label").click()
    self.driver.find_element(By.ID, "Descrizione").click()
    self.driver.find_element(By.ID, "Descrizione").send_keys("il locatore non è stato coerente con l\'annuncio proposto sul sito,  rendendo l\'annuncio presente non veritiero")
    self.driver.find_element(By.CSS_SELECTOR, ".bottone > .btn").click()